# Generated by Django 5.0.1 on 2024-01-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.TextField(max_length=200),
        ),
    ]
