# Generated by Django 5.0.1 on 2024-01-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_gallary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member_description',
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
