# Generated by Django 5.0.1 on 2024-01-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_gallary', '0002_remove_team_member_description_team_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_img',
            field=models.ImageField(upload_to='team/'),
        ),
    ]
