# Generated by Django 5.0.1 on 2024-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=400)),
                ('durations', models.CharField(max_length=200)),
                ('funded_by', models.CharField(max_length=100)),
                ('funding_amount', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.TextField()),
                ('pages', models.CharField(blank=True, max_length=255, null=True)),
                ('journal', models.TextField()),
                ('cited_by', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('link', models.URLField()),
            ],
        ),
    ]
