# Generated by Django 5.0.1 on 2024-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=400)),
                ('resource_description', models.TextField()),
                ('resource_img', models.ImageField(upload_to='resource_img/')),
                ('pdf_file', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
