# Generated by Django 5.0.1 on 2024-01-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_project', '0002_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
